"""tasks: remove batch_size field (now stored directly in code)

Revision ID: b4173d74b35d
Revises: 97245ee448de
Create Date: 2025-05-20 11:15:22.341030

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4173d74b35d'
down_revision: Union[str, None] = '97245ee448de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'batch_size')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('batch_size', sa.INTEGER(), nullable=False))
    # ### end Alembic commands ###
