"""remove unnecessary fields from task and file upload tables

Revision ID: 68e215c6d7e7
Revises: 8ccf9749373b
Create Date: 2025-03-10 13:05:41.388362

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68e215c6d7e7'
down_revision: Union[str, None] = '8ccf9749373b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('s3_file_upload', 'output_count')
    op.drop_column('task', 's3_bucket')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('s3_bucket', sa.VARCHAR(), nullable=False))
    op.add_column('s3_file_upload', sa.Column('output_count', sa.INTEGER(), nullable=False))
    # ### end Alembic commands ###
