"""add another datasource + task state

Revision ID: 97245ee448de
Revises: 1c21702a0fbb
Create Date: 2025-04-15 11:55:31.103450

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "97245ee448de"
down_revision: Union[str, None] = "1c21702a0fbb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

OLD_DATA_SOURCE_ENUM = sa.Enum(
    "spotify-api",
    "spotify-internal",
    name="data_source",
    create_constraint=True,
)

NEW_DATA_SOURCE_ENUM = sa.Enum(
    "spotify-api",
    "spotify-internal",
    # NOTE: NEW DATA SOURCE
    "dummy-api",
    name="data_source",
    create_constraint=True,
)

OLD_TASK_STATUS_ENUM = sa.Enum(
    "pending",
    "running",
    "done",
    "error",
    "paused",
    name="data_fetching_task_status",
    create_constraint=True,
)


NEW_TASK_STATUS_ENUM = sa.Enum(
    "pending",
    "running",
    "done",
    "error",
    "paused",
    # NOTE: NEW TASK STATE
    "pausing",
    name="data_fetching_task_status",
    create_constraint=True,
)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("task") as batch_op:
        batch_op.alter_column(
            "data_source",
            existing_type=OLD_DATA_SOURCE_ENUM,
            type_=NEW_DATA_SOURCE_ENUM,
            existing_nullable=False,
        )

        batch_op.alter_column(
            "status",
            existing_type=OLD_TASK_STATUS_ENUM,
            type_=NEW_TASK_STATUS_ENUM,
            existing_nullable=False,
        )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("task") as batch_op:
        batch_op.alter_column(
            "data_source",
            existing_type=NEW_DATA_SOURCE_ENUM,
            type_=OLD_DATA_SOURCE_ENUM,
            existing_nullable=False,
        )
        batch_op.alter_column(
            "status",
            existing_type=NEW_TASK_STATUS_ENUM,
            type_=OLD_TASK_STATUS_ENUM,
            existing_nullable=False,
        )
