"""add new data source

Revision ID: 1c21702a0fbb
Revises: 08ad1fb90e7d
Create Date: 2025-03-25 12:09:17.514001

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1c21702a0fbb"
down_revision: Union[str, None] = "08ad1fb90e7d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - didn't work out-of-the-box ###
    # op.alter_column('task', 'data_source',
    #            existing_type=sa.VARCHAR(length=11),
    #            type_=sa.Enum('spotify-api', 'spotify-internal', name='data_source', create_constraint=True),
    #            existing_nullable=False)
    with op.batch_alter_table("task") as batch_op:
        batch_op.alter_column(
            "data_source",
            existing_type=sa.VARCHAR(length=11),
            type_=sa.Enum(
                "spotify-api",
                "spotify-internal",
                name="data_source",
                create_constraint=True,
            ),
            existing_nullable=False,
        )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "task",
        "data_source",
        existing_type=sa.Enum(
            "spotify-api",
            "spotify-internal",
            name="data_source",
            create_constraint=True,
        ),
        type_=sa.VARCHAR(length=11),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
