"""remove success_count from tasks (stored in task progress DB now)

Revision ID: 81d702035d08
Revises: 68e215c6d7e7
Create Date: 2025-03-12 09:33:43.450584

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81d702035d08'
down_revision: Union[str, None] = '68e215c6d7e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'success_count')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('success_count', sa.INTEGER(), nullable=False))
    # ### end Alembic commands ###
