"""remove redundant lines_written_to_current_output_file from task table

Revision ID: 08ad1fb90e7d
Revises: 81d702035d08
Create Date: 2025-03-12 10:43:20.508112

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08ad1fb90e7d'
down_revision: Union[str, None] = '81d702035d08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'lines_written_to_current_output_file')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('lines_written_to_current_output_file', sa.INTEGER(), nullable=False))
    # ### end Alembic commands ###
