services:
  scraper-api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - S3_KEY_ID
      - S3_SECRET
      - S3_ENDPOINT_URL
      - S3_BUCKET
      - CREDENTIALS_API_URL
      - LOG_LEVEL
      # needed for virtual X server (used by programs requiring an X server for automated GUI interactions, e.g. browser scrapers in non-headless mode)
      - DISPLAY=:99
    ports:
      # to run n replicas, add --scale scraper-api=n to docker compose up command and modify port range below (currently single port 4200) to allow each container to get its own port if you need more than max_port - min_port servicesi
      # afaik there's no way to predefine ports for each replica upon startup :/
      - 4200:80
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./api-client-config.yml:/app/api-client-config.yml
      - ./alembic:/app/alembic
      - ./alembic.ini:/app/alembic.ini
