services:
  scraper-api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - S3_KEY_ID
      - S3_SECRET
      - S3_ENDPOINT_URL
      - S3_BUCKET
      # needed for xvfb
      - DISPLAY=:99
    ports:
      - 4200:80
    volumes:
      - ./api-client-config.yml:/app/api-client-config.yml
      - ./alembic:/app/alembic
      - ./alembic.ini:/app/alembic.ini
