- name: Copy API client config to hosts
  hosts: scrapers
  gather_facts: no
  vars_prompt:
    - name: "ansible_become_password"
      prompt: "Enter your sudo password (required for removal of dir)"
      private: yes

  pre_tasks:
    - name: Load CSV data from spotify_creds.csv
      # Reads the CSV file and converts it into a list of dictionaries.
      set_fact:
        csv_data: "{{ lookup('file', 'spotify_creds.csv') | community.general.from_csv() }}"
      delegate_to: localhost
      run_once: true

  tasks:
    - name: Set host-specific credentials from CSV
      # This sets host-specific facts by indexing into csv_data using the host's position
      set_fact:
        client_id: "{{ csv_data[ groups['scrapers'].index(inventory_hostname) | int ].client_id }}"
        client_secret: "{{ csv_data[ groups['scrapers'].index(inventory_hostname) | int ].client_secret }}"
      vars:
        host_index: "{{ ansible_play_batch.index(inventory_hostname) }}"

    - name: Remove the directory for api-client-config.yml
      ansible.builtin.file:
        path: /home/wucloud/async-scraper-api/api-server/api-client-config.yml
        state: absent
      become: true

    - name: Copy the api-client-config.yml file to the host
      template:
        src: templates/api-client-config.yml.j2
        dest: ~/async-scraper-api/api-server/api-client-config.yml